In [44]:
from pathlib import Path
import pandas as pd

folder = Path("./exam_form_data_dec_2025")

df = pd.concat(
    [
        pd.read_excel(file).assign(source_file=file.stem)
        for file in folder.glob("*.xlsx")
    ],
    ignore_index=True
)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6458 entries, 0 to 6457
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   roll_no          6458 non-null   int64
 1   registration_no  6458 non-null   object
 2   admission_no     6458 non-null   object
 3   enroll_no        0 non-null      float64
 4   student_name     6458 non-null   object
 5   father_name      6455 non-null   object
 6   mother_name      6447 non-null   object
 7   student_batch    6458 non-null   int64
 8   college_id       6458 non-null   int64
 9   college_name     6458 non-null   object
 10  branch_id        6458 non-null   int64
 11  branch_name      6458 non-null   object
 12  exam_type        6458 non-null   object
 13  sch_id           6458 non-null   int64
 14  scheme_title     6458 non-null   object
 15  sem_year         6458 non-null   int64
 16  exam_Form_Date   6458 non-null   object
 17  source_file      6458 non-null   object
dtypes: float64(1), int64(6), object(11)
memory usage: 908.3+ KB

In [50]:
df.to_csv("/home/dharm/exam_form_data_dec_2025_compiled_full.csv", index=False)

In [ ]:
# df =df.rename(columns= {
#     'rollNo': 'roll_no',
#     'registration No.': 'registration_no',
#     'admissiono No.': 'admission_no',
#     'enroll No.': 'enroll_no',
#     'studentName': 'student_name',
#     'fatherName': 'father_name',
#     'motherName': 'mother_name',
#     'studentBatch': 'student_batch',
#     'collegeId': 'college_id',
#     'collegeName': 'college_name',
#     'branchId': 'branch_id',
#     'branchName': 'branch_name',
#     'examType': 'exam_type',
#     'schId': 'sch_id',
#     'schemeTitle': 'scheme_title',
#     'sem_Year': 'sem_year',
#     'examFormDate':'exam_Form_Date',
    
    
    
    
    
# })

In [20]:
df['schemeTitle']

0       B.Sc. (Non Medical),5,2025                    ...
1       B.Sc. (Non Medical),5,2025                    ...
2       B.Sc. (Non Medical),5,2025                    ...
3       B.Sc. (Non Medical),5,2025                    ...
4       B.Sc. (Non Medical),5,2025                    ...
                              ...
6453    M.Sc. ( Chemistry),1,2025                     ...
6454    M.Sc. ( Chemistry),1,2025                     ...
6455    M.Sc. ( Chemistry),1,2025                     ...
6456    M.Sc. ( Chemistry),1,2025                     ...
6457    M.Sc. ( Chemistry),1,2025                     ...
Name: schemeTitle, Length: 6458, dtype: object

In [21]:
df["schemeTitle"] = (
    df["schemeTitle"]
    .str.split(",", n=2)
    .str[:2]
    .str.join(",")
)

In [22]:
df['examFormDate'].unique()

array(['04 Nov 2025', '11 Nov 2025', '29 Oct 2025', '07 Nov 2025',
       '10 Nov 2025', '13 Nov 2025', '26 Nov 2025', '14 Nov 2025',
       '17 Nov 2025', '12 Nov 2025', '09 Dec 2025', '01 Dec 2025',
       '19 Nov 2025', '28 Oct 2025', '03 Nov 2025', '24 Oct 2025',
       '03 Mar 2026', '27 Oct 2025', '06 Nov 2025', '06 Dec 2025',
       '15 Nov 2025', '21 Nov 2025', '10 Dec 2025', '22 Nov 2025',
       '02 Dec 2025', '08 Nov 2025', '25 Oct 2025', '15 Oct 2025',
       '18 Oct 2025', '02 Mar 2026', '09 Mar 2026', '17 Dec 2025',
       '20 Nov 2025', '18 Nov 2025', '28 Nov 2025', '08 Dec 2025',
       '05 Dec 2025', '03 Dec 2025', '11 Feb 2026', '30 Oct 2025',
       '15 Dec 2025', '16 Oct 2025', '06 Mar 2026', '10 Feb 2026'],
      dtype=object)

In [23]:
df["schemeTitle"].sample(5)

1084    B.A. ( General),3
5055     M.A. (History),1
4744                BCA,3
658     B.A. ( General),3
4162    B.A. ( General),1
Name: schemeTitle, dtype: object

In [24]:
df[["Class", "Sem"]] = df["schemeTitle"].str.split(",", n=1, expand=True)

In [25]:
df.groupby(["Class", "Sem"])["rollNo"].count().to_csv("/home/dharm/exam_form_data_dec_2025_compiled.csv")

In [26]:
df['Sem'].unique()

array(['5', '3', '1'], dtype=object)

In [27]:
df['Sem'] = df['Sem'].astype(int)

In [28]:
df['Sem'].unique()

array([5, 3, 1])

In [29]:
df_sem1=df[df['Sem']==1]

In [30]:
df_sem1.sample()

,rollNo,registration No.,admissiono No.,enroll No.,studentName,fatherName,motherName,studentBatch,collegeId,collegeName,branchId,branchName,examType,schId,schemeTitle,sem_Year,examFormDate,source_file,Class,Sem
2606,2512007,5111-2022-1267,2022/LCA0/591,NaN,Sumanpreet Kaur,Pritam Singh,Harjit Kaur,2025,1,"Guru Nanak College, Budhlada",5,M.Sc. (Physics),Regular,58,"M.Sc. (Physics),1",1,04 Nov 2025,msc physics 1,M.Sc. (Physics),1

In [31]:
df_sem1.groupby(["Class", "Sem"])["rollNo"].count().to_csv("/home/dharm/exam_form_data_dec_2025_compiled_sem1_only.csv")

In [32]:
df_not_sem1 = df[df['Sem']!=1]

In [33]:
df_not_sem1.sample()

,rollNo,registration No.,admissiono No.,enroll No.,studentName,fatherName,motherName,studentBatch,collegeId,collegeName,branchId,branchName,examType,schId,schemeTitle,sem_Year,examFormDate,source_file,Class,Sem
4738,24120005,5111-2024-233,2024/LCA0/1777,NaN,Parvinder Singh,Labh Singh,Amarjeet Kair,2024,1,"Guru Nanak College, Budhlada",40,BCA,Regular,12,"BCA,3",3,24 Oct 2025,bca 3,BCA,3

In [34]:
df_not_sem1.groupby(["Class", "Sem"])["rollNo"].count().to_csv("/home/dharm/exam_form_data_dec_2025_compiled_not_sem1.csv")